name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-preview.4.20258.7
    - name: Install dependencies
      run: dotnet restore
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 14.x
    - run: cd "./Client/Scripts"
    - name: Install Node.js dependencies
      run: npm install
    - run: cd ../..
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish the client
      run: dotnet publish "./Client/TaskPlanner.Client.csproj" -c Release --self-contained -o "./publish"
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: "client"
        path: "./publish"
